### ISSUE TITLE
Usage RGP Table

### ISSUE THREAD

**Issue by plengkeek** [stephansmit/rgptable_cfx#1]
Hi Stephan,

Didn't know how to contact you but have experience implementing these tables in CFX? I am aiming to use them for homogeneous multiphase to represent the liquid and vapor phase in a flow. Currently I am struggling with clipping and extrapolation issues. Could you contact me on: p.lengkeek@student.tudelft.nl?

Cheers

**Comment by stephansmit** [comment]
@plengkeek long time ago that I used this code. But I think if you have clipping and extrapolation issues you need to make your table bigger as it will be outside of your table domain. However, during the convergence of your solution you can expect that to happen. Welcome to the black-art of cfd simulation ;). Try restarting from a converged solution (either first order or using EOS). In my research i had to first converge with EOS and only after that could I use the RGP. Visualize your convergence to see if there are specific spots where it is having difficulties... My advice: dont go for RGP/second order in one go, but build complexity and converged solutions on at the time and use them as a starting point.
